# -*- coding: utf-8 -*-
"""Plotting_data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rI8RH49DOSKFOKUA7YiLB-QT0P2XLirX
"""

#Installing matplotlib 
pip install matplotlib

import matplotlib.pyplot as plt
x = [ i for i in range(10)]
print(x)

y = [2*i for i in range(10)]
print(y)

plt.plot(x,y)

plt.xlabel('x-axis')
plt.ylabel('y-axis')
plt.plot(x,y)

#plotting scatterplot graph
plt.scatter(x,y)